### ISSUE TITLE
(mugshot:22748)

### ISSUE THREAD

**Issue by machadofguilherme** [bluesabre/mugshot#16]
(mugshot:17483): Gtk-WARNING **: 01:06:37.420: Content added to the action area of a dialog using header bars

(mugshot:17483): Gtk-WARNING **: 01:06:37.420: Content added to the action area of a dialog using header bars
Traceback (most recent call last):
  File "/bin/mugshot", line 36, in <module>
    mugshot.main()
  File "/usr/lib/python3.9/site-packages/mugshot/__init__.py", line 47, in main
    window = MugshotWindow.MugshotWindow()
  File "/usr/lib/python3.9/site-packages/mugshot_lib/Window.py", line 51, in __new__
    builder = get_builder('MugshotWindow')
  File "/usr/lib/python3.9/site-packages/mugshot_lib/helpers.py", line 43, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3.9/site-packages/mugshot_lib/Builder.py", line 92, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'

**Comment by bluesabre** [comment]
This was fixed in Mugshot 0.4.3. Please reopen if you encounter this issue in the current release. Thanks!

https://github.com/bluesabre/mugshot/commit/643b3d005a8865c961b836aeae4c1f76711646e9
